server:
  port: 8083

spring:
  application:
    name: orderservice

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    consumer:
      isolation-level: read_committed

jwt:
  secret-key: ${JWT_SECRET}